// config.js — default categories, categorisation rules, and app constants.

export const DEFAULT_CATEGORIES = [
  { name: 'EC-Violin',           group: 'Extracurricular' },
  { name: 'EC-Singing',          group: 'Extracurricular' },
  { name: 'EC-Dance',            group: 'Extracurricular' },
  { name: 'EC-UWH',              group: 'Extracurricular' },
  { name: 'EC-Activity',         group: 'Extracurricular' },
  { name: 'School Fee',          group: 'Education' },
  { name: 'Groceries',           group: 'Living' },
  { name: 'Food',                group: 'Living' },
  { name: 'Dining Out',          group: 'Living' },
  { name: 'Fuel',                group: 'Transport' },
  { name: 'Car',                 group: 'Transport' },
  { name: 'Commutation',         group: 'Transport' },
  { name: 'Mortgage',            group: 'Housing' },
  { name: 'Utilities',           group: 'Housing' },
  { name: 'Insurance',           group: 'Housing' },
  { name: 'Council',             group: 'Housing' },
  { name: 'Health',              group: 'Wellbeing' },
  { name: 'Shopping',            group: 'Lifestyle' },
  { name: 'Entertainment',       group: 'Lifestyle' },
  { name: 'Travel',              group: 'Lifestyle' },
  { name: 'Interbank Transfers', group: 'Transfers' },
  { name: 'Salary',              group: 'Income' },
  { name: 'Income',              group: 'Income' },
  { name: 'Fees & Interest',     group: 'Banking' },
  { name: 'Cash',                group: 'Banking' },
  { name: 'Other',               group: 'Other' },
  { name: 'Uncategorised',       group: 'Other' },
];

// Ordered rules — first keyword found in the (upper-cased) description wins.
// Tuned for NZ merchants seen in AMEX / ANZ statements.
export const DEFAULT_RULES = [
  // Extracurricular
  { kw: 'VIOLIN',            cat: 'EC-Violin' },
  { kw: 'SINGING',           cat: 'EC-Singing' },
  { kw: 'VOCAL',             cat: 'EC-Singing' },
  { kw: 'CARNATIC',          cat: 'EC-Singing' },
  { kw: 'DANCE',             cat: 'EC-Dance' },
  { kw: 'BHARATANATYAM',     cat: 'EC-Dance' },
  { kw: 'UWH',               cat: 'EC-UWH' },
  { kw: 'UNDERWATER HOCKEY', cat: 'EC-UWH' },
  { kw: 'DUKEOFEDNZ',        cat: 'EC-Activity' },
  { kw: 'DUKE OF ED',        cat: 'EC-Activity' },
  { kw: 'SPLASH AND DASH',   cat: 'EC-Activity' },
  { kw: 'SPLASH N DASH',     cat: 'EC-Activity' },
  { kw: 'SPLASH & DASH',     cat: 'EC-Activity' },
  { kw: 'SPLASHNDASH',       cat: 'EC-Activity' },
  // Education
  { kw: 'SCHOOL',            cat: 'School Fee' },
  { kw: 'COLLEGE',           cat: 'School Fee' },
  { kw: 'EDUCATIONAL',       cat: 'School Fee' },
  { kw: 'KINDERGARTEN',      cat: 'School Fee' },
  { kw: 'DELTA EDUCATIONAL', cat: 'School Fee' },
  { kw: 'WGC',               cat: 'School Fee' },
  { kw: 'WELLINGTON GIRLS',  cat: 'School Fee' },
  // Groceries
  { kw: 'PAK N SAVE',        cat: 'Groceries' },
  { kw: 'PAKNSAVE',          cat: 'Groceries' },
  { kw: 'WOOLWORTHS',        cat: 'Groceries' },
  { kw: 'COUNTDOWN',         cat: 'Groceries' },
  { kw: 'NEW WORLD',         cat: 'Groceries' },
  { kw: 'FRESH CHOICE',      cat: 'Groceries' },
  { kw: 'MOORE WILSON',      cat: 'Groceries' },
  { kw: 'SUPERMARKET',       cat: 'Groceries' },
  // Fuel
  { kw: 'WAITOMO',           cat: 'Fuel' },
  { kw: 'BP CONNECT',        cat: 'Fuel' },
  { kw: 'GULL',              cat: 'Fuel' },
  { kw: 'Z ENERGY',          cat: 'Fuel' },
  { kw: 'MOBIL ',            cat: 'Fuel' },
  { kw: 'CALTEX',            cat: 'Fuel' },
  { kw: 'GAS ',              cat: 'Fuel' },
  { kw: 'U-GO',              cat: 'Fuel' },
  { kw: 'NPD',               cat: 'Fuel' },
  { kw: 'ALLIED',            cat: 'Fuel' },
  // Dining
  { kw: 'MCDONALD',          cat: 'Dining Out' },
  { kw: 'KFC',               cat: 'Dining Out' },
  { kw: 'SUBWAY',            cat: 'Dining Out' },
  { kw: 'PIZZA',             cat: 'Dining Out' },
  { kw: 'UBER EATS',         cat: 'Dining Out' },
  { kw: 'DOORDASH',          cat: 'Dining Out' },
  { kw: 'STARBUCKS',         cat: 'Dining Out' },
  { kw: 'CAFE',              cat: 'Dining Out' },
  { kw: 'RESTAURANT',        cat: 'Dining Out' },
  { kw: 'BURGER',            cat: 'Dining Out' },
  // Transport / car
  { kw: 'UBER',              cat: 'Commutation' },
  { kw: 'METLINK',           cat: 'Commutation' },
  { kw: 'SNAPPER',           cat: 'Commutation' },
  { kw: 'AT HOP',            cat: 'Commutation' },
  { kw: 'PARKING',           cat: 'Car' },
  { kw: 'WILSON PARKING',    cat: 'Car' },
  { kw: 'VTNZ',              cat: 'Car' },
  { kw: 'WOF',               cat: 'Car' },
  { kw: 'REPCO',             cat: 'Car' },
  { kw: 'SUPERCHEAP',        cat: 'Car' },
  // Housing
  { kw: 'MORTGAGE',          cat: 'Mortgage' },
  { kw: 'HOME LOAN',         cat: 'Mortgage' },
  { kw: 'LOAN PMT',          cat: 'Mortgage' },
  { kw: 'LOAN PAYMENT',      cat: 'Mortgage' },
  { kw: 'LUMP SUM PAYMENT',  cat: 'Mortgage' },
  { kw: 'LUMP SUM',          cat: 'Mortgage' },
  { kw: 'SPARK',             cat: 'Utilities' },
  { kw: 'VODAFONE',          cat: 'Utilities' },
  { kw: 'ONE NZ',            cat: 'Utilities' },
  { kw: '2DEGREES',          cat: 'Utilities' },
  { kw: 'TWO DEGREES',       cat: 'Utilities' },
  { kw: 'SKINNY',            cat: 'Utilities' },
  { kw: 'CONTACT ENERGY',    cat: 'Utilities' },
  { kw: 'MERCURY',           cat: 'Utilities' },
  { kw: 'GENESIS',           cat: 'Utilities' },
  { kw: 'ELECTRIC KIWI',     cat: 'Utilities' },
  { kw: 'TRUSTPOWER',        cat: 'Utilities' },
  { kw: 'INTERNET',          cat: 'Utilities' },
  { kw: 'WATER',             cat: 'Utilities' },
  { kw: 'CITY COUNCIL',      cat: 'Council' },
  { kw: 'DISTRICT COUNCIL',  cat: 'Council' },
  { kw: 'PORIRUA CITY',      cat: 'Council' },
  { kw: 'COUNCIL',           cat: 'Council' },
  { kw: 'TOWER',             cat: 'Insurance' },
  { kw: 'AA INSURANCE',      cat: 'Insurance' },
  { kw: 'AMI',               cat: 'Insurance' },
  { kw: 'STATE INSURANCE',   cat: 'Insurance' },
  { kw: 'INSURANCE',         cat: 'Insurance' },
  // Health
  { kw: 'CHEMIST',           cat: 'Health' },
  { kw: 'PHARMACY',          cat: 'Health' },
  { kw: 'UNICHEM',           cat: 'Health' },
  { kw: 'MEDICAL',           cat: 'Health' },
  { kw: 'DOCTOR',            cat: 'Health' },
  { kw: 'DENTAL',            cat: 'Health' },
  { kw: 'DENTIST',           cat: 'Health' },
  { kw: 'MATT BARKER',       cat: 'Health' },
  { kw: 'PHYSIO',            cat: 'Health' },
  // Shopping
  { kw: 'BUNNINGS',          cat: 'Shopping' },
  { kw: 'MITRE 10',          cat: 'Shopping' },
  { kw: 'REBEL',             cat: 'Shopping' },
  { kw: 'KMART',             cat: 'Shopping' },
  { kw: 'WAREHOUSE',         cat: 'Shopping' },
  { kw: 'AMAZON',            cat: 'Shopping' },
  { kw: 'ALIBABA',           cat: 'Shopping' },
  { kw: 'ALIEXPRESS',        cat: 'Shopping' },
  { kw: 'BRISCOES',          cat: 'Shopping' },
  { kw: 'FARMERS',           cat: 'Shopping' },
  // Entertainment / travel
  { kw: 'NETFLIX',           cat: 'Entertainment' },
  { kw: 'SPOTIFY',           cat: 'Entertainment' },
  { kw: 'DISNEY',            cat: 'Entertainment' },
  { kw: 'PRIME VIDEO',       cat: 'Entertainment' },
  { kw: 'CINEMA',            cat: 'Entertainment' },
  { kw: 'EVENT CINEMAS',     cat: 'Entertainment' },
  { kw: 'AIR NZ',            cat: 'Travel' },
  { kw: 'AIRNZ',             cat: 'Travel' },
  { kw: 'JETSTAR',           cat: 'Travel' },
  { kw: 'SINGAPOREAIR',      cat: 'Travel' },
  { kw: 'SINGAPORE AIR',     cat: 'Travel' },
  { kw: 'QANTAS',            cat: 'Travel' },
  { kw: 'EMIRATES',          cat: 'Travel' },
  { kw: 'CATHAY',            cat: 'Travel' },
  { kw: 'BOOKING.COM',       cat: 'Travel' },
  { kw: 'AIRBNB',            cat: 'Travel' },
  { kw: 'HOTEL',             cat: 'Travel' },
  { kw: 'MERIDIEN',          cat: 'Travel' },
  { kw: 'EXPEDIA',           cat: 'Travel' },
  // Banking / transfers / income
  { kw: 'TRANSFER',          cat: 'Interbank Transfers' },
  { kw: 'ANNUAL CARD FEE',   cat: 'Fees & Interest' },
  { kw: 'CARD FEE',          cat: 'Fees & Interest' },
  { kw: 'INTEREST',          cat: 'Fees & Interest' },
  { kw: 'ATM',               cat: 'Cash' },
  { kw: 'CASH',              cat: 'Cash' },
  { kw: 'PAYMENT - THANK YOU', cat: 'Interbank Transfers' },
  { kw: 'SALARY',            cat: 'Salary' },
  { kw: 'PAYROLL',           cat: 'Salary' },
  { kw: 'WAGES',             cat: 'Salary' },
  { kw: 'PAY - ',            cat: 'Salary' },
  { kw: 'DIRECT CREDIT',     cat: 'Income' },
  { kw: 'INTEREST EARNED',   cat: 'Income' },
  { kw: 'INLAND REVENUE',    cat: 'Income' },
  { kw: 'REFUND',            cat: 'Income' },
  { kw: 'DIVIDEND',          cat: 'Income' },
];

export const DATA_FILE = 'porul-data.json';
export const LEGACY_DATA_FILES = ['fintide-data.json'];
export const SCHEMA_VERSION = 1;
export const RULES_VERSION = 2;
