// config.js — default categories, categorisation rules, and app constants.

// Three-level taxonomy: Group → Category → Subcategory (leaf).
// Transactions are tagged with the leaf subcategory name.
export const TAXONOMY = {
  'Housing & Living': {
    'Shelter & Rent': ['Mortgage Payments', 'Rent', 'Body Corp / HOA Fees', 'Property Rates / Taxes'],
    'Utilities': ['Electricity', 'Gas / Heating', 'Water & Sewage', 'Internet & Broadband', 'Mobile / Cell Plans'],
    'Home Care & Upgrades': ['Lawn Care & Gardening', 'Plumbing & Hardware', 'Major Repairs & Renovations', 'Green / Solar Initiatives'],
    'Furnishings & Housewares': ['Furniture', 'Appliances', 'Decor & Plants', 'Kitchenware'],
  },
  'Food & Household': {
    'Groceries': ['Supermarkets', 'Produce Markets', 'Specialty & Imported Foods', 'Household Supplies / Cleaning'],
    'Dining & Social': ['Restaurants', 'Takeaway & Delivery', 'Coffee Shops & Cafes', 'Bars & Alcohol'],
  },
  'Transportation & Vehicles': {
    'Vehicle Expenses': ['Fuel / EV Charging', 'Vehicle Service & Maintenance', 'Parking & Tolls', 'Registration & Licensing'],
    'Transit & Rideshare': ['Public Transit (Bus/Train/Ferry)', 'Rideshare & Taxis'],
  },
  'Education & Academic': {
    'School & Tuition': ['Tuition / School Fees', 'Technology & Device Fees', 'Exam & Registration Fees'],
    'Academic Supplies': ['Uniforms & Apparel', 'Textbooks & Reading', 'Stationeries & Materials'],
  },
  'Extra-Curriculars, Sports & Enrichment': {
    'Active & Athletics': ['Sports Clubs & Registration', 'Coaching & Training'],
    'Arts & Music': ['Music & Dance Lessons', 'Instrument Rentals & Supplies', 'Performing Arts Clubs'],
    'Youth Activities': ['Scouting / Youth Clubs', 'Summer & Holiday Camps', 'Science Fair / Academic Competitions'],
  },
  'Events, Gifts & Celebrations': {
    'Occasions & Holidays': ['Birthday Parties & Hostings', 'Weddings & Formal Events', 'Holiday & Festival Supplies'],
    'Gifting': ['Birthday Gifts', 'Holiday / Christmas Gifts', 'Charitable Donations & Causes'],
  },
  'Travel & Holidays': {
    'Transit & Lodging': ['Flights & Rail', 'Hotels & Airbnb', 'Campsites & Water Taxis', 'Car Rentals'],
    'Trip Spending': ['Excursions & Activities', 'Dining While Away', 'Travel Insurance'],
  },
  'Personal Care, Health & Lifestyle': {
    'Health & Medical': ['Doctor & Specialist Visits', 'Dental & Eyecare', 'Pharmacy & Prescriptions', 'Health Insurance'],
    'Personal Care & Wellness': ['Haircuts & Salon', 'Cosmetics & Toiletries', 'Gym & Fitness Memberships'],
    'Shopping & Entertainment': ['Clothing & Shoes', 'Sports Gear & Outfitting', 'Tech & Gadgets', 'Streaming & Digital Subscriptions', 'Books & Media'],
  },
  'Financial, Debt & Savings': {
    'Financial Obligations': ['Personal / Student Loan Repayments', 'Credit Card Interest', 'Bank & Transaction Fees', 'Insurance (General)'],
    'Savings & Wealth': ['Emergency Fund Contributions', 'General Savings', 'Investments / Stocks', 'Retirement'],
  },
  'Income': {
    'Income': ['Salary', 'Other Income'],
  },
  'Transfers & System': {
    'Internal Transfers': ['Credit Card Payments', 'Account-to-Account Transfers'],
    'Banking': ['Cash & ATM', 'Bank Deposit'],
    'Uncategorized': ['Needs Manual Review', 'Other'],
  },
};

// Sentinel leaf for anything not yet classified.
export const UNCATEGORISED = 'Needs Manual Review';

// Flattened leaf list: { name (subcategory), category, group }.
export const DEFAULT_CATEGORIES = Object.entries(TAXONOMY).flatMap(([group, cats]) =>
  Object.entries(cats).flatMap(([category, subs]) => subs.map(name => ({ name, category, group }))));

// Legacy (v1) category name → new leaf subcategory, for migrating saved data.
export const CATEGORY_ALIASES = {
  'Groceries': 'Supermarkets', 'Food': 'Supermarkets',
  'Dining Out': 'Restaurants',
  'Fuel': 'Fuel / EV Charging', 'Car': 'Vehicle Service & Maintenance',
  'Commutation': 'Public Transit (Bus/Train/Ferry)',
  'Mortgage': 'Mortgage Payments', 'Utilities': 'Electricity',
  'Insurance': 'Insurance (General)', 'Council': 'Property Rates / Taxes',
  'Health': 'Doctor & Specialist Visits', 'Shopping': 'Clothing & Shoes',
  'Entertainment': 'Streaming & Digital Subscriptions', 'Travel': 'Flights & Rail',
  'Interbank Transfers': 'Account-to-Account Transfers',
  'Salary': 'Salary', 'Income': 'Other Income',
  'Fees & Interest': 'Bank & Transaction Fees', 'Cash': 'Cash & ATM',
  'School Fee': 'Tuition / School Fees',
  'EC-Violin': 'Music & Dance Lessons', 'EC-Singing': 'Music & Dance Lessons',
  'EC-Dance': 'Music & Dance Lessons', 'EC-UWH': 'Sports Clubs & Registration',
  'EC-Activity': 'Scouting / Youth Clubs', 'Work': 'Other',
  'Uncategorised': 'Needs Manual Review',
};

// Ordered keyword → leaf-subcategory rules. First keyword found in the description wins.
export const DEFAULT_RULES = [
  // User-defined priority mappings (checked first; first keyword found wins).
  { kw: 'LOAN DRAWDOWN', cat: 'Mortgage Payments' },
  { kw: 'INWARD SOLUTIONS', cat: 'Account-to-Account Transfers' },
  { kw: 'MICROSOFT NEW ZEALAN', cat: 'Salary' },
  { kw: 'MATURITY', cat: 'Bank Deposit' },
  { kw: ' SAL ', cat: 'Salary' },
  { kw: 'DEPOSIT', cat: 'Bank Deposit' },
  // Extra-curriculars
  { kw: 'VIOLIN', cat: 'Music & Dance Lessons' },
  { kw: 'SINGING', cat: 'Music & Dance Lessons' },
  { kw: 'VOCAL', cat: 'Music & Dance Lessons' },
  { kw: 'CARNATIC', cat: 'Music & Dance Lessons' },
  { kw: 'DANCE', cat: 'Music & Dance Lessons' },
  { kw: 'BHARATANATYAM', cat: 'Music & Dance Lessons' },
  { kw: 'UWH', cat: 'Sports Clubs & Registration' },
  { kw: 'UNDERWATER HOCKEY', cat: 'Sports Clubs & Registration' },
  { kw: 'SPLASH AND DASH', cat: 'Sports Clubs & Registration' },
  { kw: 'SPLASH N DASH', cat: 'Sports Clubs & Registration' },
  { kw: 'SPLASH & DASH', cat: 'Sports Clubs & Registration' },
  { kw: 'SPLASHNDASH', cat: 'Sports Clubs & Registration' },
  { kw: 'DUKEOFEDNZ', cat: 'Scouting / Youth Clubs' },
  { kw: 'DUKE OF ED', cat: 'Scouting / Youth Clubs' },
  // Education
  { kw: 'SCHOOL', cat: 'Tuition / School Fees' },
  { kw: 'COLLEGE', cat: 'Tuition / School Fees' },
  { kw: 'EDUCATIONAL', cat: 'Tuition / School Fees' },
  { kw: 'KINDERGARTEN', cat: 'Tuition / School Fees' },
  { kw: 'DELTA EDUCATIONAL', cat: 'Tuition / School Fees' },
  { kw: 'WGC', cat: 'Tuition / School Fees' },
  { kw: 'WELLINGTON GIRLS', cat: 'Tuition / School Fees' },
  // Groceries
  { kw: 'PAK N SAVE', cat: 'Supermarkets' },
  { kw: 'PAKNSAVE', cat: 'Supermarkets' },
  { kw: 'WOOLWORTHS', cat: 'Supermarkets' },
  { kw: 'COUNTDOWN', cat: 'Supermarkets' },
  { kw: 'NEW WORLD', cat: 'Supermarkets' },
  { kw: 'FRESH CHOICE', cat: 'Supermarkets' },
  { kw: 'MOORE WILSON', cat: 'Supermarkets' },
  { kw: 'SUPERMARKET', cat: 'Supermarkets' },
  { kw: 'SPICE RACK', cat: 'Specialty & Imported Foods' },
  { kw: 'UNCLE BILLS', cat: 'Specialty & Imported Foods' },
  { kw: 'UNCLE BILL', cat: 'Specialty & Imported Foods' },
  // Fuel / vehicle
  { kw: 'WAITOMO', cat: 'Fuel / EV Charging' },
  { kw: 'BP CONNECT', cat: 'Fuel / EV Charging' },
  { kw: 'GULL', cat: 'Fuel / EV Charging' },
  { kw: 'Z ENERGY', cat: 'Fuel / EV Charging' },
  { kw: 'MOBIL ', cat: 'Fuel / EV Charging' },
  { kw: 'CALTEX', cat: 'Fuel / EV Charging' },
  { kw: 'GAS ', cat: 'Fuel / EV Charging' },
  { kw: 'U-GO', cat: 'Fuel / EV Charging' },
  { kw: 'NPD', cat: 'Fuel / EV Charging' },
  { kw: 'ALLIED', cat: 'Fuel / EV Charging' },
  { kw: 'REPCO', cat: 'Vehicle Service & Maintenance' },
  { kw: 'SUPERCHEAP', cat: 'Vehicle Service & Maintenance' },
  { kw: 'PARKING', cat: 'Parking & Tolls' },
  { kw: 'WILSON PARKING', cat: 'Parking & Tolls' },
  { kw: 'VTNZ', cat: 'Registration & Licensing' },
  { kw: 'WOF', cat: 'Registration & Licensing' },
  // Dining
  { kw: 'MCDONALD', cat: 'Takeaway & Delivery' },
  { kw: 'KFC', cat: 'Takeaway & Delivery' },
  { kw: 'SUBWAY', cat: 'Takeaway & Delivery' },
  { kw: 'PIZZA', cat: 'Takeaway & Delivery' },
  { kw: 'UBER EATS', cat: 'Takeaway & Delivery' },
  { kw: 'DOORDASH', cat: 'Takeaway & Delivery' },
  { kw: 'BURGER', cat: 'Takeaway & Delivery' },
  { kw: 'STARBUCKS', cat: 'Coffee Shops & Cafes' },
  { kw: 'CAFE', cat: 'Coffee Shops & Cafes' },
  { kw: 'RESTAURANT', cat: 'Restaurants' },
  { kw: 'PUNJABI', cat: 'Restaurants' },
  { kw: 'CUISINE', cat: 'Restaurants' },
  { kw: 'MASALA', cat: 'Restaurants' },
  { kw: 'KITCHEN', cat: 'Restaurants' },
  { kw: 'TANDOOR', cat: 'Restaurants' },
  // Transit / rideshare
  { kw: 'UBER', cat: 'Rideshare & Taxis' },
  { kw: 'METLINK', cat: 'Public Transit (Bus/Train/Ferry)' },
  { kw: 'SNAPPER', cat: 'Public Transit (Bus/Train/Ferry)' },
  { kw: 'AT HOP', cat: 'Public Transit (Bus/Train/Ferry)' },
  // Housing / utilities
  { kw: 'MORTGAGE', cat: 'Mortgage Payments' },
  { kw: 'HOME LOAN', cat: 'Mortgage Payments' },
  { kw: 'LOAN PMT', cat: 'Mortgage Payments' },
  { kw: 'LOAN PAYMENT', cat: 'Mortgage Payments' },
  { kw: 'LUMP SUM PAYMENT', cat: 'Mortgage Payments' },
  { kw: 'LUMP SUM', cat: 'Mortgage Payments' },
  { kw: 'SPARK', cat: 'Mobile / Cell Plans' },
  { kw: 'VODAFONE', cat: 'Mobile / Cell Plans' },
  { kw: 'ONE NZ', cat: 'Mobile / Cell Plans' },
  { kw: '2DEGREES', cat: 'Mobile / Cell Plans' },
  { kw: 'TWO DEGREES', cat: 'Mobile / Cell Plans' },
  { kw: 'SKINNY', cat: 'Mobile / Cell Plans' },
  { kw: 'CONTACT ENERGY', cat: 'Electricity' },
  { kw: 'MERCURY', cat: 'Electricity' },
  { kw: 'GENESIS', cat: 'Electricity' },
  { kw: 'ELECTRIC KIWI', cat: 'Electricity' },
  { kw: 'TRUSTPOWER', cat: 'Electricity' },
  { kw: 'INTERNET', cat: 'Internet & Broadband' },
  { kw: 'WATER', cat: 'Water & Sewage' },
  { kw: 'CITY COUNCIL', cat: 'Property Rates / Taxes' },
  { kw: 'DISTRICT COUNCIL', cat: 'Property Rates / Taxes' },
  { kw: 'PORIRUA CITY', cat: 'Property Rates / Taxes' },
  { kw: 'COUNCIL', cat: 'Property Rates / Taxes' },
  { kw: 'BUNNINGS', cat: 'Plumbing & Hardware' },
  { kw: 'MITRE 10', cat: 'Plumbing & Hardware' },
  // Insurance
  { kw: 'TOWER', cat: 'Insurance (General)' },
  { kw: 'AA INSURANCE', cat: 'Insurance (General)' },
  { kw: 'AMI', cat: 'Insurance (General)' },
  { kw: 'STATE INSURANCE', cat: 'Insurance (General)' },
  { kw: 'INSURANCE', cat: 'Insurance (General)' },
  // Health
  { kw: 'CHEMIST', cat: 'Pharmacy & Prescriptions' },
  { kw: 'PHARMACY', cat: 'Pharmacy & Prescriptions' },
  { kw: 'UNICHEM', cat: 'Pharmacy & Prescriptions' },
  { kw: 'MEDICAL', cat: 'Doctor & Specialist Visits' },
  { kw: 'DOCTOR', cat: 'Doctor & Specialist Visits' },
  { kw: 'PHYSIO', cat: 'Doctor & Specialist Visits' },
  { kw: 'DENTAL', cat: 'Dental & Eyecare' },
  { kw: 'DENTIST', cat: 'Dental & Eyecare' },
  { kw: 'MATT BARKER', cat: 'Dental & Eyecare' },
  { kw: 'SOUTHERN CROSS', cat: 'Health Insurance' },
  // Shopping / entertainment
  { kw: 'REBEL', cat: 'Sports Gear & Outfitting' },
  { kw: 'KMART', cat: 'Clothing & Shoes' },
  { kw: 'WAREHOUSE', cat: 'Clothing & Shoes' },
  { kw: 'BRISCOES', cat: 'Kitchenware' },
  { kw: 'FARMERS', cat: 'Clothing & Shoes' },
  { kw: 'AMAZON', cat: 'Tech & Gadgets' },
  { kw: 'ALIBABA', cat: 'Tech & Gadgets' },
  { kw: 'ALIEXPRESS', cat: 'Tech & Gadgets' },
  { kw: 'NETFLIX', cat: 'Streaming & Digital Subscriptions' },
  { kw: 'SPOTIFY', cat: 'Streaming & Digital Subscriptions' },
  { kw: 'DISNEY', cat: 'Streaming & Digital Subscriptions' },
  { kw: 'PRIME VIDEO', cat: 'Streaming & Digital Subscriptions' },
  { kw: 'CINEMA', cat: 'Books & Media' },
  { kw: 'EVENT CINEMAS', cat: 'Books & Media' },
  // Travel
  { kw: 'AIR NZ', cat: 'Flights & Rail' },
  { kw: 'AIRNZ', cat: 'Flights & Rail' },
  { kw: 'JETSTAR', cat: 'Flights & Rail' },
  { kw: 'SINGAPOREAIR', cat: 'Flights & Rail' },
  { kw: 'SINGAPORE AIR', cat: 'Flights & Rail' },
  { kw: 'QANTAS', cat: 'Flights & Rail' },
  { kw: 'EMIRATES', cat: 'Flights & Rail' },
  { kw: 'CATHAY', cat: 'Flights & Rail' },
  { kw: 'BOOKING.COM', cat: 'Hotels & Airbnb' },
  { kw: 'AIRBNB', cat: 'Hotels & Airbnb' },
  { kw: 'HOTEL', cat: 'Hotels & Airbnb' },
  { kw: 'MERIDIEN', cat: 'Hotels & Airbnb' },
  { kw: 'EXPEDIA', cat: 'Hotels & Airbnb' },
  // Banking / transfers / income
  { kw: 'TRANSFER', cat: 'Account-to-Account Transfers' },
  { kw: 'PAYMENT - THANK YOU', cat: 'Credit Card Payments' },
  { kw: 'ANNUAL CARD FEE', cat: 'Bank & Transaction Fees' },
  { kw: 'CARD FEE', cat: 'Bank & Transaction Fees' },
  { kw: 'INTEREST', cat: 'Credit Card Interest' },
  { kw: 'ATM', cat: 'Cash & ATM' },
  { kw: 'CASH', cat: 'Cash & ATM' },
  { kw: 'SALARY', cat: 'Salary' },
  { kw: 'PAYROLL', cat: 'Salary' },
  { kw: 'WAGES', cat: 'Salary' },
  { kw: 'PAY - ', cat: 'Salary' },
  { kw: 'DIRECT CREDIT', cat: 'Other Income' },
  { kw: 'INTEREST EARNED', cat: 'Other Income' },
  { kw: 'INLAND REVENUE', cat: 'Other Income' },
  { kw: 'REFUND', cat: 'Other Income' },
  { kw: 'DIVIDEND', cat: 'Investments / Stocks' },
];

export const DATA_FILE = 'porul-data.json';
export const LEGACY_DATA_FILES = ['fintide-data.json'];
export const SCHEMA_VERSION = 1;
export const RULES_VERSION = 7;
